# Generated by Django 3.2.5 on 2021-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lot_images/'),
        ),
    ]
