# Generated by Django 3.2.5 on 2021-09-14 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210913_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
