# Generated by Django 3.2.5 on 2021-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='lots',
            field=models.ManyToManyField(blank=True, default=None, to='auctions.Lot'),
        ),
    ]
