# Generated by Django 3.2.5 on 2021-09-17 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_watchlist_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_lot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='lots',
            field=models.ManyToManyField(blank=True, to='auctions.Lot'),
        ),
    ]
